### ISSUE TITLE
config 문제

### ISSUE THREAD

**Issue by giwk2** [Hwan-I/motion_keypoint#2]
안녕하세요 데이콘에서 보고 따라해보려고 시도중입니다.

일단 패키지 설치하고 가중치 다운받고 train.py 를 돌려보았는데

C:\jupyterProject\Untitled Folder\HRNet_bbox>python tools/train.py --cfg experiments/coco/hrnet/w48_384x288_adam_lr1e-3_03_origin.yaml --test_option False
Traceback (most recent call last):
  File "tools/train.py", line 29, in <module>
    from config import cfg
  File "C:\jupyterProject\Untitled Folder\HRNet_bbox\tools\..\lib\config\__init__.py", line 7, in <module>
    from .default import _C as cfg
  File "C:\jupyterProject\Untitled Folder\HRNet_bbox\tools\..\lib\config\default.py", line 14, in <module>
    from yacs.config import CfgNode as CN
ModuleNotFoundError: No module named 'yacs'

저 config import 하는 부분이 안되어서 혹시 어떤 부분이 문제인지 알수 있을까요??

깃허브를 처음 사용해보아서 죄송합니다. ㅠ

**Comment by Hwan-I** [comment]
괜찮습니다! 혹시 Readme.md 대로 셋팅을 했는데도 이런 오류가 발생했나요? 일단 yacs 패키지가 없다는 오류라서 아래 링크대로 설치해보셔도 될 것 같습니다.
https://githubmemory.com/repo/lzccccc/SMOKE/issues/25

**Comment by giwk2** [comment]
정말 감사합니다~!! 덕분에 돌려보고 있습니다. 
감사합니다.
